import { Product } from "@/types/product";

const DISCLAIMER =
  "For research use only. Not for human or veterinary use. Not intended for diagnostic or therapeutic purposes. Keep out of reach of children.";

export const products: Product[] = [
  {
    id: "semaglutide",
    slug: "semaglutide",
    name: "Semaglutide",
    category: "GLP-1 Agonists",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 285,
    salePrice: 245,
    shortDescription:
      "A GLP-1 receptor agonist analog used in metabolic research. Studies glucose-dependent insulin secretion and body weight regulation pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "semaglutide.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "igf1-lr3",
    slug: "igf1-lr3",
    name: "IGF1-LR3",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water with 0.1% acetic acid",
    originalPrice: 298,
    salePrice: 258,
    shortDescription:
      "Long R3 insulin-like growth factor-1 with extended half-life. Used in cellular growth and muscle tissue proliferation research.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "igf1-lr3.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "matrixyl-3000",
    slug: "matrixyl-3000",
    name: "Matrixyl 3000",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A palmitoyl dipeptide-3 and matrikine signaling complex. Research focuses on collagen synthesis stimulation and ECM protein production.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "matrixyl-3000.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "tesamorelin",
    slug: "tesamorelin",
    name: "Tesamorelin",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 14 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 285,
    salePrice: 245,
    shortDescription:
      "A synthetic analog of growth hormone-releasing hormone (GHRH). Used in GH secretion and metabolic regulation research.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "tesamorelin.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "tirzepatide",
    slug: "tirzepatide",
    name: "Tirzepatide",
    category: "GLP-1 Agonists",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 188,
    salePrice: 148,
    shortDescription:
      "A dual GIP and GLP-1 receptor agonist. Used in type 2 diabetes and obesity mechanism research via incretin-based metabolic pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "tirzepatide.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "ipamorelin-acetate",
    slug: "ipamorelin-acetate",
    name: "Ipamorelin Acetate",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 325,
    salePrice: 285,
    shortDescription:
      "A selective growth hormone secretagogue and ghrelin receptor agonist. Research focuses on GH pulsatile release and appetite regulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "ipamorelin-acetate.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "pnc-27",
    slug: "pnc-27",
    name: "PNC-27",
    category: "Other Research Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in DMSO",
    originalPrice: 138,
    salePrice: 98,
    shortDescription:
      "A p53-related peptide that selectively targets cancer cell membranes. Used in oncology research for selective cytotoxicity mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "pnc-27.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "acetyl-hexapeptide-38",
    slug: "acetyl-hexapeptide-38",
    name: "Acetyl Hexapeptide 38",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A signal peptide used in adipogenesis and fat storage research. Studies focus on modulating adipocyte differentiation pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "acetyl-hexapeptide-38.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "hexapeptide-10-serilesine",
    slug: "hexapeptide-10-serilesine",
    name: "Hexapeptide-10 / Serilesine",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A laminin-derived hexapeptide used in skin adhesion and cellular matrix research. Studies laminin-5 receptor interactions and integrin signaling.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "hexapeptide0-serilesine4.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "snap-8",
    slug: "snap-8",
    name: "Snap-8 / Acetyl Octapeptide-3",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "An octapeptide analog of SNAP-25 used in neuromuscular junction research. Studies vesicle-membrane fusion and neurotransmitter release mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "snap-8-acetyl-octapeptide-3x.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "ace-031",
    slug: "ace-031",
    name: "ACE-031",
    category: "Muscle Research",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 14 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 185,
    salePrice: 145,
    shortDescription:
      "A fusion protein based on activin receptor type IIA. Research focuses on myostatin inhibition and muscle mass regulation pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "ace-031.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "thymosin-alpha1",
    slug: "thymosin-alpha1",
    name: "Thymosin Alpha 1",
    category: "Immune Support",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 300,
    salePrice: 260,
    shortDescription:
      "A naturally occurring thymic peptide used in immune system modulation research. Studies T-cell maturation, NK cell activation, and immune response pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "thymosin-alpha1.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "selank",
    slug: "selank",
    name: "Selank",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 285,
    salePrice: 245,
    shortDescription:
      "A heptapeptide analog of tuftsin used in anxiolytic and nootropic research. Studies GABA receptor modulation and cognitive enhancement mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "selank.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "sermorelin-acetate",
    slug: "sermorelin-acetate",
    name: "Sermorelin Acetate",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 14 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 199,
    salePrice: 159,
    shortDescription:
      "A 29-amino acid GHRH analog used in growth hormone secretion research. Studies pituitary somatotroph stimulation and GH axis regulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "sermorelin-acetate.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "tripeptide-29",
    slug: "tripeptide-29",
    name: "Tripeptide-29",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 149,
    salePrice: 109,
    shortDescription:
      "A collagen tripeptide (Gly-Pro-Hyp) used in ECM and wound healing research. Studies collagen precursor synthesis and fibroblast activity.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "tripeptide-29.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "fragment-176-191",
    slug: "fragment-176-191",
    name: "Fragment 176-191",
    category: "Fat Loss Research",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "A 16-amino acid fragment of human growth hormone used in lipolysis research. Studies fat metabolism regulation and adipocyte receptor interactions.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "fragment7691.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "palmitoyl-tripeptide-5",
    slug: "palmitoyl-tripeptide-5",
    name: "Palmitoyl Tripeptide-5",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A biomimetic peptide that activates TGF-β pathways. Research focuses on collagen synthesis and tissue remodeling mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "palmitoyl-tripeptide-5.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "thymosin-beta4",
    slug: "thymosin-beta4",
    name: "Thymosin Beta 4",
    category: "Healing & Recovery",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 345,
    salePrice: 305,
    shortDescription:
      "A ubiquitous 43-amino acid peptide used in tissue repair and angiogenesis research. Studies actin sequestration, wound healing, and cardiac regeneration.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "thymosin-beta4.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "semax",
    slug: "semax",
    name: "Semax",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 185,
    salePrice: 145,
    shortDescription:
      "A synthetic ACTH analog used in neuroprotection and cognitive function research. Studies BDNF regulation and neuroplasticity mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "semax.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "cjc-1295",
    slug: "cjc-1295",
    name: "CJC-1295",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 325,
    salePrice: 285,
    shortDescription:
      "A 30-amino acid GHRH analog with DAC modification. Used in long-acting GH secretion and IGF-1 elevation pathway research.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "cjc295.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "bpc-157",
    slug: "bpc-157",
    name: "BPC-157",
    category: "Healing & Recovery",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water with 0.1% acetic acid",
    originalPrice: 298,
    salePrice: 258,
    shortDescription:
      "A 15-amino acid partial sequence of body protection compound. Research focuses on angiogenesis, tendon repair, and gut mucosal protection.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "bpc57.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "vip",
    slug: "vip",
    name: "VIP (Vasoactive Intestinal Peptide)",
    category: "Other Research Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 178,
    salePrice: 138,
    shortDescription:
      "A 28-amino acid neuropeptide used in smooth muscle and immune research. Studies vasodilation, bronchodilation, and anti-inflammatory mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "vip.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "vilon",
    slug: "vilon",
    name: "Vilon",
    category: "Anti-Aging",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "A dipeptide (Lys-Glu) derived from the thymus used in aging and immune regulation research. Studies peptide bioregulation and longevity mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "vilon.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "vialox",
    slug: "vialox",
    name: "Vialox (Pentapeptide-3V)",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "A synthetic pentapeptide analog of waglerin-1. Research studies nicotinic acetylcholine receptor antagonism and muscle contraction mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "vialox-pentapeptide-3v.jpg",
    featured: false,
    inStock: true,
  },
];

export const getFeaturedProducts = (): Product[] =>
  products.filter((p) => p.featured);

export const getProductBySlug = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);

export const getProductsByCategory = (category: string): Product[] =>
  products.filter((p) => p.category === category);

export const getAllCategories = (): string[] =>
  [...new Set(products.map((p) => p.category))].sort();
