import { Product } from "@/types/product";

const DISCLAIMER =
  "For research use only. Not for human or veterinary use. Not intended for diagnostic or therapeutic purposes. Keep out of reach of children.";

export const products: Product[] = [
  {
    id: "semaglutide",
    slug: "semaglutide",
    name: "Semaglutide",
    category: "GLP-1 Agonists",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 285,
    salePrice: 245,
    shortDescription:
      "A GLP-1 receptor agonist analog used in metabolic research. Studies glucose-dependent insulin secretion and body weight regulation pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "semaglutide.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "igf1-lr3",
    slug: "igf1-lr3",
    name: "IGF1-LR3",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water with 0.1% acetic acid",
    originalPrice: 298,
    salePrice: 258,
    shortDescription:
      "Long R3 insulin-like growth factor-1 with extended half-life. Used in cellular growth and muscle tissue proliferation research.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "igf1-lr3.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "matrixyl-3000",
    slug: "matrixyl-3000",
    name: "Matrixyl 3000",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A palmitoyl dipeptide-3 and matrikine signaling complex. Research focuses on collagen synthesis stimulation and ECM protein production.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "matrixyl-3000.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "tesamorelin",
    slug: "tesamorelin",
    name: "Tesamorelin",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 14 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 285,
    salePrice: 245,
    shortDescription:
      "A synthetic analog of growth hormone-releasing hormone (GHRH). Used in GH secretion and metabolic regulation research.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "tesamorelin.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "tirzepatide",
    slug: "tirzepatide",
    name: "Tirzepatide",
    category: "GLP-1 Agonists",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 188,
    salePrice: 148,
    shortDescription:
      "A dual GIP and GLP-1 receptor agonist. Used in type 2 diabetes and obesity mechanism research via incretin-based metabolic pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "tirzepatide.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "ipamorelin-acetate",
    slug: "ipamorelin-acetate",
    name: "Ipamorelin Acetate",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 325,
    salePrice: 285,
    shortDescription:
      "A selective growth hormone secretagogue and ghrelin receptor agonist. Research focuses on GH pulsatile release and appetite regulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "ipamorelin-acetate.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "pnc-27",
    slug: "pnc-27",
    name: "PNC-27",
    category: "Other Research Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in DMSO",
    originalPrice: 138,
    salePrice: 98,
    shortDescription:
      "A p53-related peptide that selectively targets cancer cell membranes. Used in oncology research for selective cytotoxicity mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "pnc-27.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "acetyl-hexapeptide-38",
    slug: "acetyl-hexapeptide-38",
    name: "Acetyl Hexapeptide 38",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A signal peptide used in adipogenesis and fat storage research. Studies focus on modulating adipocyte differentiation pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "acetyl-hexapeptide-38.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "hexapeptide-10-serilesine",
    slug: "hexapeptide-10-serilesine",
    name: "Hexapeptide-10 / Serilesine",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A laminin-derived hexapeptide used in skin adhesion and cellular matrix research. Studies laminin-5 receptor interactions and integrin signaling.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "hexapeptide0-serilesine4.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "snap-8",
    slug: "snap-8",
    name: "Snap-8 / Acetyl Octapeptide-3",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "An octapeptide analog of SNAP-25 used in neuromuscular junction research. Studies vesicle-membrane fusion and neurotransmitter release mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "snap-8-acetyl-octapeptide-3x.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "ace-031",
    slug: "ace-031",
    name: "ACE-031",
    category: "Muscle Research",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 14 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 185,
    salePrice: 145,
    shortDescription:
      "A fusion protein based on activin receptor type IIA. Research focuses on myostatin inhibition and muscle mass regulation pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "ace-031.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "thymosin-alpha1",
    slug: "thymosin-alpha1",
    name: "Thymosin Alpha 1",
    category: "Immune Support",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 300,
    salePrice: 260,
    shortDescription:
      "A naturally occurring thymic peptide used in immune system modulation research. Studies T-cell maturation, NK cell activation, and immune response pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "thymosin-alpha1.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "selank",
    slug: "selank",
    name: "Selank",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 285,
    salePrice: 245,
    shortDescription:
      "A heptapeptide analog of tuftsin used in anxiolytic and nootropic research. Studies GABA receptor modulation and cognitive enhancement mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "selank.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "sermorelin-acetate",
    slug: "sermorelin-acetate",
    name: "Sermorelin Acetate",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 14 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 199,
    salePrice: 159,
    shortDescription:
      "A 29-amino acid GHRH analog used in growth hormone secretion research. Studies pituitary somatotroph stimulation and GH axis regulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "sermorelin-acetate.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "tripeptide-29",
    slug: "tripeptide-29",
    name: "Tripeptide-29",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 149,
    salePrice: 109,
    shortDescription:
      "A collagen tripeptide (Gly-Pro-Hyp) used in ECM and wound healing research. Studies collagen precursor synthesis and fibroblast activity.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "tripeptide-29.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "fragment-176-191",
    slug: "fragment-176-191",
    name: "Fragment 176-191",
    category: "Fat Loss Research",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "A 16-amino acid fragment of human growth hormone used in lipolysis research. Studies fat metabolism regulation and adipocyte receptor interactions.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "fragment7691.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "palmitoyl-tripeptide-5",
    slug: "palmitoyl-tripeptide-5",
    name: "Palmitoyl Tripeptide-5",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A biomimetic peptide that activates TGF-β pathways. Research focuses on collagen synthesis and tissue remodeling mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "palmitoyl-tripeptide-5.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "thymosin-beta4",
    slug: "thymosin-beta4",
    name: "Thymosin Beta 4",
    category: "Healing & Recovery",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 345,
    salePrice: 305,
    shortDescription:
      "A ubiquitous 43-amino acid peptide used in tissue repair and angiogenesis research. Studies actin sequestration, wound healing, and cardiac regeneration.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "thymosin-beta4.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "semax",
    slug: "semax",
    name: "Semax",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 185,
    salePrice: 145,
    shortDescription:
      "A synthetic ACTH analog used in neuroprotection and cognitive function research. Studies BDNF regulation and neuroplasticity mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "semax.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "cjc-1295",
    slug: "cjc-1295",
    name: "CJC-1295",
    category: "Growth Hormone Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 325,
    salePrice: 285,
    shortDescription:
      "A 30-amino acid GHRH analog with DAC modification. Used in long-acting GH secretion and IGF-1 elevation pathway research.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "cjc295.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "bpc-157",
    slug: "bpc-157",
    name: "BPC-157",
    category: "Healing & Recovery",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water with 0.1% acetic acid",
    originalPrice: 298,
    salePrice: 258,
    shortDescription:
      "A 15-amino acid partial sequence of body protection compound. Research focuses on angiogenesis, tendon repair, and gut mucosal protection.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "bpc57.jpg",
    featured: true,
    inStock: true,
  },
  {
    id: "vip",
    slug: "vip",
    name: "VIP (Vasoactive Intestinal Peptide)",
    category: "Other Research Peptides",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 178,
    salePrice: 138,
    shortDescription:
      "A 28-amino acid neuropeptide used in smooth muscle and immune research. Studies vasodilation, bronchodilation, and anti-inflammatory mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "vip.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "vilon",
    slug: "vilon",
    name: "Vilon",
    category: "Anti-Aging",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "A dipeptide (Lys-Glu) derived from the thymus used in aging and immune regulation research. Studies peptide bioregulation and longevity mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "vilon.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "vialox",
    slug: "vialox",
    name: "Vialox (Pentapeptide-3V)",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "A synthetic pentapeptide analog of waglerin-1. Research studies nicotinic acetylcholine receptor antagonism and muscle contraction mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "vialox-pentapeptide-3v.jpg",
    featured: false,
    inStock: true,
  },

  // ── Page 2 products ──────────────────────────────────────────────────────────

  {
    id: "vesugen",
    slug: "vesugen",
    name: "Vesugen",
    category: "Anti-Aging",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 196,
    salePrice: 156,
    shortDescription:
      "A vascular bioregulator tripeptide used in cardiovascular and endothelial aging research. Studies peptide regulation of vascular wall function.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "vesugen.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "vesilut",
    slug: "vesilut",
    name: "Vesilut",
    category: "Anti-Aging",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A urinary bladder bioregulator peptide used in urogenital tissue aging research. Studies smooth muscle cell regulation and organ-specific peptide bioregulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "vesilut.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "thyrotropin-trh",
    slug: "thyrotropin-trh",
    name: "Thyrotropin TRH",
    category: "Other Research Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 188,
    salePrice: 148,
    shortDescription:
      "Thyrotropin-releasing hormone, a hypothalamic tripeptide. Used in neuroendocrine and HPT axis research studying TSH secretion and thyroid function regulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "thyrotropin-trh.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "thymalin",
    slug: "thymalin",
    name: "Thymalin",
    category: "Immune Support",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A thymic polypeptide complex used in immune system modulation and aging research. Studies T-cell differentiation, NK cell activity, and thymic peptide bioregulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "thymalin.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "thymagen",
    slug: "thymagen",
    name: "Thymagen",
    category: "Immune Support",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 188,
    salePrice: 148,
    shortDescription:
      "A thymic tetrapeptide (His-Asp-Gly-Val) used in immune regulation research. Studies T-lymphocyte differentiation and immunomodulatory peptide bioregulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "thymagen.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "testagen",
    slug: "testagen",
    name: "Testagen",
    category: "Anti-Aging",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 128,
    salePrice: 88,
    shortDescription:
      "A testicular gland bioregulator tetrapeptide used in male reproductive aging research. Studies gonadotropin regulation and testicular cell function.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "testagen.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "syn-coll",
    slug: "syn-coll",
    name: "Syn-Coll",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "A palmitoyl tripeptide-5 analog used in collagen synthesis and skin aging research. Studies TGF-β pathway activation and extracellular matrix remodeling.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "syn-coll.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "ptd-dbm",
    slug: "ptd-dbm",
    name: "PTD-DBM",
    category: "Healing & Recovery",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in DMSO",
    originalPrice: 158,
    salePrice: 118,
    shortDescription:
      "A cell-penetrating peptide fused with a Dishevelled-binding motif. Used in Wnt/β-catenin pathway research studying hair follicle regeneration mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "ptd-dbm.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "prostamax",
    slug: "prostamax",
    name: "Prostamax",
    category: "Other Research Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 188,
    salePrice: 148,
    shortDescription:
      "A prostate gland bioregulator peptide used in urogenital research. Studies prostate cell differentiation, glandular tissue regulation, and organ-specific bioregulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "prostamax.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "pinealon",
    slug: "pinealon",
    name: "Pinealon",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 188,
    salePrice: 148,
    shortDescription:
      "A pineal gland tripeptide (Glu-Asp-Arg) used in circadian rhythm and neuroprotection research. Studies melatonin regulation, retinal function, and brain aging mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "pinealon.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "pentapeptide-18",
    slug: "pentapeptide-18",
    name: "Pentapeptide-18",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 135,
    salePrice: 95,
    shortDescription:
      "Also known as Leuphasyl, an enkephalin-like pentapeptide used in neuromuscular junction research. Studies opioid receptor interaction and expression-line inhibition mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "leuphasyl.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "peg-mgf",
    slug: "peg-mgf",
    name: "PEG-MGF",
    category: "Muscle Research",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "PEGylated mechano growth factor with extended half-life. Used in muscle satellite cell activation and tissue repair research via IGF-1 splice variant pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "peg-mgf.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "pe-22-28",
    slug: "pe-22-28",
    name: "PE-22-28",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 128,
    salePrice: 88,
    shortDescription:
      "A truncated spadin analog with TREK-1 channel antagonist activity. Used in antidepressant mechanism research studying serotonin system and neuroplasticity pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "pe-22-28.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "pancragen",
    slug: "pancragen",
    name: "Pancragen",
    category: "Other Research Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 128,
    salePrice: 88,
    shortDescription:
      "A pancreatic bioregulator tetrapeptide used in islet cell function and metabolic aging research. Studies insulin secretion regulation and pancreatic tissue bioregulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "pancragen.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "pal-ghk",
    slug: "pal-ghk",
    name: "Pal-GHK",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 135,
    salePrice: 95,
    shortDescription:
      "Palmitoyl tripeptide-1 (Pal-Gly-His-Lys) used in collagen and elastin synthesis research. Studies ECM protein production and skin structural protein regulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "pal-ghk.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "pal-ahk",
    slug: "pal-ahk",
    name: "Pal-AHK",
    category: "Cosmetic Peptides",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in water",
    originalPrice: 135,
    salePrice: 95,
    shortDescription:
      "Palmitoyl tripeptide-3 (Pal-Ala-His-Lys) used in hair follicle and scalp research. Studies follicle stem cell activation and hair growth factor signaling pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "pal-ahk.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "p21",
    slug: "p21",
    name: "P21",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 178,
    salePrice: 138,
    shortDescription:
      "A humanin-derived peptide analog with enhanced neuroprotective activity. Used in neurodegeneration and cognitive decline research via STAT3 and IGF-1 receptor pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "p21.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "n-acetyl-semax",
    slug: "n-acetyl-semax",
    name: "N-Acetyl Semax",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 138,
    salePrice: 98,
    shortDescription:
      "An acetylated analog of Semax with enhanced bioavailability. Used in BDNF upregulation, neuroprotection, and cognitive enhancement mechanism research.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "n-acetyl-semax.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "n-acetyl-selank",
    slug: "n-acetyl-selank",
    name: "N-Acetyl Selank",
    category: "Cognitive & Nootropic",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "An acetylated Selank analog with improved stability. Used in anxiolytic mechanism and GABAergic modulation research, studying cognitive and stress response pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "n-acetyl-selank.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "mgf",
    slug: "mgf",
    name: "MGF",
    category: "Muscle Research",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "Mechano growth factor, an IGF-1 splice variant. Used in satellite cell recruitment and muscle hypertrophy research studying mechanotransduction and tissue repair pathways.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "mgf.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "ll-37",
    slug: "ll-37",
    name: "LL-37",
    category: "Immune Support",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "The only human cathelicidin antimicrobial peptide. Used in innate immunity and wound healing research studying membrane disruption, biofilm inhibition, and immunomodulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "ll-37.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "livagen",
    slug: "livagen",
    name: "Livagen",
    category: "Anti-Aging",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 178,
    salePrice: 138,
    shortDescription:
      "A liver and immune bioregulator tetrapeptide used in hepatocellular aging research. Studies chromatin remodeling, gene expression regulation, and liver tissue bioregulation.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "livagen.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "kpv",
    slug: "kpv",
    name: "KPV",
    category: "Healing & Recovery",
    purity: ">98% by HPLC",
    storage: "Lyophilized: -20°C. Reconstituted: 4°C, use within 28 days.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 148,
    salePrice: 108,
    shortDescription:
      "A C-terminal tripeptide of alpha-MSH (Lys-Pro-Val) with potent anti-inflammatory activity. Used in gut inflammation, wound healing, and NF-κB pathway research.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "kpv.jpg",
    featured: false,
    inStock: true,
  },
  {
    id: "humanin",
    slug: "humanin",
    name: "Humanin",
    category: "Anti-Aging",
    purity: ">98% by HPLC",
    storage: "Store at -20°C. Stable for 24 months when stored properly.",
    form: "Lyophilized powder",
    solubility: "Soluble in sterile water",
    originalPrice: 198,
    salePrice: 158,
    shortDescription:
      "A mitochondria-derived cytoprotective peptide used in neurodegeneration and longevity research. Studies anti-apoptotic signaling, metabolic regulation, and age-related disease mechanisms.",
    fullDescription: "Full research description — to be added from original product page.",
    disclaimer: DISCLAIMER,
    imageFilename: "humanin.jpg",
    featured: false,
    inStock: true,
  },
];

export const getFeaturedProducts = (): Product[] =>
  products.filter((p) => p.featured);

export const getProductBySlug = (slug: string): Product | undefined =>
  products.find((p) => p.slug === slug);

export const getProductsByCategory = (category: string): Product[] =>
  products.filter((p) => p.category === category);

export const getAllCategories = (): string[] =>
  [...new Set(products.map((p) => p.category))].sort();
